name: all_clash

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'all_clash.py'
  schedule:
    - cron: '0 */3 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限设置
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # 使用SSH方式克隆仓库
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        persist-credentials: true
        
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests tqdm
        pip install python-dotenv tqdm
        
    - name: Run collection script
      env:
          URL_SOURCE: ${{ secrets.URL_SOURCE }}
          
      run: python subscribe/all_clash.py

    - name: 提交更改
      run: |                 
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/all_clash.txt
        git add . 
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"

    - name: 拉取远程并变基
      run: |
        git pull --rebase origin main

    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        branch: main
