
name: all_clash

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'all_clash.py'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限设置
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # 使用SSH方式克隆仓库
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        persist-credentials: true
        
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: 
           pip install requests tqdm

    - name: Run collection script
      run: python subscribe/all_clash.py

    - name: 提交更改
      run: |                 
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/all_clash.txt
        git add . 
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') "
        
  
     
       
