name: Cache Management

on:
  schedule:
    - cron: '0 */1 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run_cache_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if any)
        run: pip install -r requirements.txt  # 如果有 requirements.txt

      - name: Run cache.py
        run: python subscribe/cache.py

      - name: Commit changes (if any)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated cache update" || echo "No changes to commit"
          git push
