name: Copy Data

on:
  schedule:
    # 每天 UTC 时间凌晨 2 点运行
    # 请注意：cron 表达式使用 UTC 时间。
    # 如果您希望在韩国时间（KST, UTC+9）凌晨 2 点运行，
    # 那么 UTC 时间应该是前一天的下午 5 点（17:00）。
    # 例如，如果想在 KST 2:00 AM 运行，则 cron 表达式应为 '0 17 * * *'
    - cron: '0 2 * * *' # 示例：每天 UTC 时间凌晨 2 点

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy data to subdirectory
        run: |
          chmod +x ./subscribe/copy_to_sub.sh
          ./subscribe/copy_to_sub.sh
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@noreply.github.com"
          git add .
          # 仅当有更改时才提交
          git diff --staged --quiet || git commit -m "Auto-copy data files"
          git push
