name: Run Clash Script
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
          
        run: pip install -r requirements.txt
             pip install tqdm  
             pip install pyyaml tqdm
      - name: Create data directory
        run: mkdir -p data
      - name: Run script
        run: python subscribe/clash.py
      - name: Check file
        run: |
          echo "当前目录: $(pwd)"
          if [ -f data/ss.yaml ]; then
            echo "文件 data/ss.yaml 已生成。"
          else
            echo "文件 data/ss.yaml 未生成。"
          fi
