name: Run Clash Script
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Remove existing file
        run: rm -f data/ss.yaml
      - name: Run script
        run: python subscribe/clash.py
      - name: Display file contents
        run: cat data/ss.yaml
      - name: Check if file exists
        run: |
          if [ -f data/ss.yaml ]; then
            echo "文件 data/ss.yaml 创建成功。"
          else
            echo "文件 data/ss.yaml 未找到。"
          fi
