name: Process Nodes

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq and base64
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Download files
        run: |
          curl -f -o base.txt https://github.com/qjlxg/aggregator/raw/refs/heads/main/base.txt || echo "Failed to download base.txt"
          curl -f -o ss.txt https://github.com/qjlxg/aggregator/raw/refs/heads/main/data/ss.txt || echo "Failed to download ss.txt"
          curl -f -o configtg.txt https://github.com/qjlxg/hy2/raw/refs/heads/main/configtg.txt || echo "Failed to download configtg.txt"

      - name: Check if files exist
        run: |
          if [ -f base.txt ] && [ -f ss.txt ] && [ -f configtg.txt ]; then
            echo "All files downloaded successfully."
          else
            echo "One or more files failed to download."
            exit 1
          fi

      - name: Process nodes
        run: |
          cat base.txt ss.txt configtg.txt > all_nodes.txt
          grep 'vmess://' all_nodes.txt | sed 's/vmess:\/\///g' | base64 --decode > vmess_json.txt
          jq -r '.ps' vmess_json.txt > vmess_names.txt
          grep -v 'vmess://' all_nodes.txt | grep -oP '(?<=#).*?(?=$)' > other_names.txt
          cat vmess_names.txt other_names.txt | sed 's/[^a-zA-Z0-9\u4e00-\u9fa5]//g' | sort | uniq | awk '/[\u4e00-\u9fa5]/{print $0; next} {print "Bak-"NR}' > processed_nodes.txt
          awk '{printf "Bak-%03d %s\n", NR, $0}' processed_nodes.txt | sort -n -k1.5 > data/bak.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          mkdir -p data
          git add data/bak.txt
          git commit -m "Update bak.txt" || echo "No changes to commit"
          git push origin main

      - name: Set timezone to Shanghai
        run: |
          echo "上海时间: $(TZ=Asia/Shanghai date +%Y-%m-%d' '%H:%M:%S)"
