name: Manual Run Clash Script

# 触发器：手动触发工作流
on:
  workflow_dispatch:

# 定义作业
jobs:
  run-script:
    # 使用最新的 Ubuntu 环境
    runs-on: ubuntu-latest

    # 作业步骤
    steps:
      # 1. 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 使用 Python 3.x，您可以根据需要指定具体版本，如 '3.9'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml  # 安装脚本依赖的 PyYAML 包

      # 4. 设置时区为上海时间 (Asia/Shanghai, UTC+8)
      - name: Set timezone to Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          # 验证时区设置
          date

      # 5. 运行 clash.py 脚本
      - name: Run clash.py script
        run: |
          python subscribe/clash.py
