name: Filter Clash Nodesw

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  filter_nodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 安装依赖
        run: pip install -r ./requirements.txt

      - name: 安装 pysocks
        run: pip install pysocks
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml dnspython

      - name: 创建数据目录
        run: |
          mkdir -p data
          chmod 777 data

      - name: Make Clash binary executable
        run: |
          chmod +x clash/clash-linux

      - name: Run node filtering script
        run: |
          python filter_nodes.py

      - name: 验证文件
        run: |
          # 使用绝对路径
          WORKSPACE="${GITHUB_WORKSPACE}"
          FILE_PATH="${WORKSPACE}/data/google.yaml"
          
          echo "检查文件: ${FILE_PATH}"
          
          if [ -f "${FILE_PATH}" ]; then
            echo "文件存在"
            echo "文件信息:"
            ls -l "${FILE_PATH}"
            echo "文件内容:"
            cat "${FILE_PATH}"
            echo "文件权限:"
            stat "${FILE_PATH}"
          else
            echo "文件不存在: ${FILE_PATH}"
            echo "当前目录内容:"
            ls -la "${WORKSPACE}"
            echo "data 目录内容:"
            ls -la "${WORKSPACE}/data"
            exit 1
          fi
