name: Filter Clash Nodes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  filter_nodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 安装依赖
        run: pip install -r ./requirements.txt

      - name: 安装 pysocks
        run: pip install pysocks
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml dnspython

      - name: Make Clash binary executable
        run: |
          chmod +x clash/clash-linux

      - name: Run node filtering script
        run: |
          python filter_nodes.py

      - name: Debug file location
        run: |
          echo "Current directory: $(pwd)"
          echo "List of files in current directory:"
          ls -la
          echo "List of files in data directory:"
          ls -la data/
          echo "Full path of google.yaml:"
          find $(pwd) -name "google.yaml"

      - name: Display file content
        run: |
          if [ -f "data/google.yaml" ]; then
            echo "File exists at data/google.yaml"
            echo "File content:"
            cat data/google.yaml
            echo "File size: $(stat -f%z data/google.yaml) bytes"
          else
            echo "File not found at data/google.yaml"
            exit 1
          fi
