name: filter_nodess 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */9 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 清理缓存
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: ${{ runner.os }}-cache-clear

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  
      
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
    - name: Execute Python script
      run: python filter_nodes.py
      
    - name: Setup Git
      run: |
         git config --global user.email "actions@github.com"
         git config --global user.name "GitHub Action"
         
    - name: Commit Changes
      run: |
         git config core.ignorecase false
         git config rebase.autostash true
         git pull --rebase origin main
         git add data/google.yaml
         git diff --staged --quiet || git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
         git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
