name: Custom Node Filter
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  filter_nodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: 安装依赖
        run: pip install -r ./requirements.txt
      - name: 安装 pysocks
        run: pip install pysocks
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml dnspython
      - name: 创建数据目录
        run: |
          mkdir -p data
          chmod 777 data
      - name: Make Clash binary executable
        run: |
          chmod +x clash/clash-linux
      - name: Run node filtering script
        run: |
          python filter_nodes.py
      - name: Check output file
        run: |
          if [ -f data/google.yaml ]; then
            echo "Output file exists"
            cat data/google.yaml
          else
            echo "Output file does not exist"
          fi
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: filtered-nodes
          path: data/google.yaml
