name: Daily Image Downloader

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run daily image downloader
        run: |
          python src/daily_image_downloader.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/*
          git commit -m "Update daily images" || echo "No changes to commit"
          git push origin main
