name: ji

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-subscribes-list:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: 运行 Python 脚本
        run: python ji_github_sync.py
        env:
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          GIT_BRANCH: ${{ secrets.GIT_BRANCH }}
          CONFIG_PATH: ${{ secrets.CONFIG_PATH }}
          SUBSCRIBES_PATH: ${{ secrets.SUBSCRIBES_PATH }}
          BOT: ${{ secrets.BOT }}
