name: My Workflow

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 你喜欢的 Python 版本 (例如 '3.9')

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv  # 如果你使用 .env 文件
          pip install requests beautifulsoup4

      - name: 运行脚本
        run: python ji.py
        env:
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
          SUBSCRIBE_URL: ${{ secrets.SUBSCRIBE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # 确保这个 Secret 已设置!
