name: Run URL ji

on:
  schedule:
    - cron: 0 0 * * *  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 configparser

      - name: Run Python script
        run: |
          python ji.py
        env:
          GITHUB_TOKEN: ${{ secrets.OKEN }}
