name: My Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main  # Or your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          # Install any other dependencies your project needs here
          pip install requests beautifulsoup4

      - name: Run your script
        run: python ji.py
