name:  jichang_list.txt

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间午夜运行一次
  workflow_dispatch:    # 允许手动触发

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # 重要：获取完整的历史记录

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4   # 安装 BeautifulSoup (bs4)

      - name: 运行脚本
        run: python jichang_list.py

      - name: 检查是否有更改并提交
        uses: actions/github-script@v7
        id: git-check
        with:
          script: |
            const core = require('@actions/core');
            const { execSync } = require('child_process');

            try {
              execSync('git config user.email "github-actions[bot]@users.noreply.github.com"');
              execSync('git config user.name "github-actions[bot]"');
              execSync('git add data/jichang_list.txt');

              const diff = execSync('git diff --quiet --exit-code');

              if (diff !== null) { // diff 返回 null 表示没有更改
                console.log('没有发现更改');
                core.setOutput('push', 'false');
              } else {
                console.log('发现更改，正在提交...');
                execSync('git commit -m "Update jichang_list.txt"');
                core.setOutput('push', 'true');
              }
            } catch (error) {
              console.error('Git 操作失败:', error);
              core.setOutput('push', 'false'); // 发生错误时不推送
            }

      - name: 推送更改
        if: steps.git-check.outputs.push == 'true'
        uses: ad-m/github-push-action@master   # 可以使用更新的版本
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}   # 推送到触发工作流的分支
          force: false # 避免强制推送，更安全
