name: 更新 jichang_list.txt

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间午夜运行一次
  workflow_dispatch:   # 允许手动触发

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # 重要：获取完整的历史记录

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行脚本
        run: python jichang_list.py

      - name: 检查是否有更改
        id: git-check
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/jichang_list.txt
          git diff --quiet --exit-code  # 检查是否有需要提交的更改
          if [ $? -eq 0 ]; then
            echo "没有需要提交的更改"
            echo "::set-output name=push::false"
          else
            echo "发现更改，正在提交..."
            git commit -m "Update jichang_list.txt"
            echo "::set-output name=push::true"
          fi

      - name: 推送更改
        if: steps.git-check.outputs.push == 'true'
        uses: ad-m/github-push-action@master  # 可以使用更新的版本
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}  # 推送到触发工作流的分支
          force: false # 避免强制推送，更安全
