name:  jichang_list.txt

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间午夜运行一次
  workflow_dispatch:    # 允许手动触发

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # 重要：获取完整的历史记录

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4   # 安装 BeautifulSoup (bs4)

      - name: 运行脚本
        run: python jichang_list.py

      - name: 提交更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/jichang.txt
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"

      - name: 拉取远程并变基
        run: |
          git pull --rebase origin main

      - name: 推送更改
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }} # 别忘了添加 token
