name: 更新 trial.cfg

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

jobs:
  update-trial-cfg:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4   # 安装依赖



      - name: 运行 Python 脚本
        run: |
          python jichang_list.py

      - name: 提交更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add trial.cfg
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
