name: jichang_list

on:
  schedule:
    - cron: 0 0 * * *  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Create data directory
        run: |
          mkdir -p data

      - name: Run Python script
        run: |
          python jichang_list.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/jichang_list.txt
          git commit -m "Update jichang_list.txt" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
