name: Scrape Telegram Links (Selenium - Google Only)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 00:00 运行
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # 将 Python 版本设置为 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install undetected-chromedriver selenium

    - name: Run Python script
      run: python xujw3.py

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions Bot"
        git add data/searched_links.txt
        git commit -m "Add searched Telegram links [skip ci]" || echo "No changes to commit"
        git push origin main
