# .github/workflows/scrape_telegram_requests.yml
name: Scrape Telegram Links (Requests)

on:
  workflow_dispatch: # 允许手动触发 workflow
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行 (北京时间 08:00)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        env:
          TELEGRAM_CHANNEL_URL: 'https://t.me/s/dingyue_center'  # 设置你的 Telegram 频道 URL
        run: python scrape_tg_links.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/ji2.txt
          git commit -m "Update scraped links" || echo "No changes to commit"
          git push origin main
