 
 name: Scrape TG Links
 
 on:
   workflow_dispatch:
   push:
     branches:
       - main
   schedule:
     - cron: '0 0 * * *'  # 每天午夜运行一次（可调整）
   
 
 
 jobs:
   scrape:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
       - name: Checkout code
         uses: actions/checkout@v3
 
       - name: Set up Python 3.8
         uses: actions/setup-python@v3
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
          
           python-version: '3.10'
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install requests beautifulsoup4
 
       - name: Run scraping script
       - name: Run scraper
         env:
           BASE_URL: https://t.me/dingyue_center 
         run: |
           python scrape_tg_links.py
 
       - name: Commit changes
         run: |
           python script.py
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add data/t.txt
           git commit -m "Update t.txt with latest links" || echo "No changes to commit"
           git push origin main
