name: Scrape Telegram URLs

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      CHANNEL_URLS: ${{ secrets.CHANNEL_URLS }}
    steps:
      - uses: actions/checkout@v2

      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: 安装 Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: 设置 ChromeDriver
        id: chromedriver
        uses: browser-actions/setup-chromedriver@v1  # 确保版本存在

      - name: 运行脚本
        run: python script.py
        env:
          CHROMEDRIVER_PATH: ${{ steps.chromedriver.outputs.chromedriver-path }}
