name: 简化抓取任务

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间8点运行

jobs:
  fetch_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 安装依赖
        run: pip install requests beautifulsoup4
      - name: 运行脚本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: https://t.me/dingyue_center
        run: python scrape_tg_links.py
