name: Scrape Telegram URLs

on:
  workflow_dispatch:  # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      CHANNEL_URLS: ${{ secrets.CHANNEL_URLS }}  # From secrets
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
          echo "Detected Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(curl -sS "http://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Failed to fetch ChromeDriver version. Using fallback: 135.0.7049.81"
            CHROMEDRIVER_VERSION="135.0.7049.81"
          else
            echo "Fetched ChromeDriver version: $CHROMEDRIVER_VERSION"
          fi
          wget -N --tries=3 --retry-connrefused "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run script
        run: python script.py
