name: 从Telegram频道抓取链接

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间8点自动跑

jobs:
  scrape_links:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装Python依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium

      - name: 安装ChromeDriver和Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          
      - name: 运行抓取脚本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          python scrape_tg_links.py
