name: search_and_save

on:
  push:
    paths:
      - 'search_and_save.py'
      - '.github/workflows/search_and_save.yml'
  workflow_dispatch: 

jobs:
  run-search:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT }}

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install requests

      - name: 执行全站搜索抓取
        env:
          BOT_TOKEN: ${{ secrets.BOT }} # 将 Secret 传入脚本
        run: python search_and_save.py

      - name: 提交并推送数据
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: 🤖 自动抓取 GitHub 域名数据 [$(date +'%Y-%m-%d %H:%M:%S')]"
            git push
          else
            echo "数据未发生变化，无需更新。"
          fi
