name: Search Proxy URLs

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - '.github/workflows/search-proxy.yml'

jobs:
  search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run search script
        run: python Search.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: proxy-urls
          path: data/u.txt
