name: Test Proxies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3  # 更新到 v3

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4  # 更新到 v4
      with:
        python-version: '3.x'

    # 安装 Python 依赖
    - name: Install dependencies
      run: |
        pip install requests pyyaml

    # 下载并安装 Clash
    - name: Download and install Clash
      run: |
        wget https://github.com/Dreamacro/clash/releases/download/v1.18.0/clash-linux-amd64-v1.18.0.gz
        gunzip clash-linux-amd64-v1.18.0.gz
        chmod +x clash-linux-amd64-v1.18.0
        sudo mv clash-linux-amd64-v1.18.0 /usr/local/bin/clash
        clash -v

    # 运行代理测试脚本
    - name: Run proxy test script
      run: python test_proxies.py

    # 调试：检查文件是否存在
    - name: Check output file
      run: ls -l data/2.yaml

    # 上传测试结果
    - name: Upload results
      uses: actions/upload-artifact@v3  # 更新到 v3
      with:
        name: available-proxies
        path: data/2.yaml
