name: Test Proxy Nodes with Clash
on: [push, workflow_dispatch]
jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 安装 Clash
        run: |
          # 下载 Clash 归档文件
          wget https://archive.org/download/github.com-Dreamacro-clash_-_2023-08-06_20-51-37/Dreamacro-clash_-_2023-08-06_20-51-37.bundle -O clash.bundle
          
          # 解压 bundle 文件（假设是 tar.gz 格式，视具体情况调整）
          tar -xzf clash.bundle
          
          # 查找并移动 Clash 二进制文件
          # 假设二进制文件名为 clash-linux-amd64，您可能需要根据实际文件名调整
          if [ -f "clash-linux-amd64" ]; then
            sudo mv clash-linux-amd64 /usr/local/bin/clash
          else
            echo "错误：未找到 Clash 二进制文件。请检查归档文件内容。"
            exit 1
          fi
          
          # 设置执行权限
          sudo chmod +x /usr/local/bin/clash
          
          # 验证安装
          clash -v

      - name: 生成 Clash 配置文件
        run: python generate_config.py

      - name: 运行测试脚本
        run: python test_nodes.py

      - name: 提交结果
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/sp.txt
          git commit -m "更新有效节点" || echo "无更改"
          git push
