name: Test Proxy Nodes with Clash
on: [push, workflow_dispatch]
jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 安装 Clash
        run: |
          # 安装 jq
          sudo apt-get update
          sudo apt-get install -y jq

          # 获取 Kuingsmile/clash-core 的最新发布信息
          RELEASE_INFO=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Kuingsmile/clash-core/releases/latest)

          # 检查 API 响应是否有效
          if [ -z "$RELEASE_INFO" ] || echo "$RELEASE_INFO" | grep -q "Not Found"; then
            echo "错误：无法获取 Kuingsmile/clash-core 的发布信息。"
            exit 1
          fi

          # 提取 Linux AMD64 二进制文件的下载链接
          DOWNLOAD_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | startswith("clash-linux-amd64") and .name | endswith(".gz")) | .browser_download_url' 2>/dev/null || echo "")
          if [ -z "$DOWNLOAD_URL" ]; then
            echo "错误：未找到适用于 Linux AMD64 的 Clash 二进制文件。"
            echo "API 响应："
            echo "$RELEASE_INFO"
            exit 1
          fi

          # 下载二进制文件
          echo "下载链接：$DOWNLOAD_URL"
          wget "$DOWNLOAD_URL" -O clash.gz

          # 解压 .gz 文件
          gunzip clash.gz

          # 移动并设置权限
          BINARY_NAME=$(ls | grep "clash-linux-amd64" || echo "clash") # 尝试匹配文件名，否则使用 "clash"
          sudo mv "$BINARY_NAME" /usr/local/bin/clash
          sudo chmod +x /usr/local/bin/clash

          # 验证安装
          clash -v

      - name: 生成 Clash 配置文件
        run: python generate_config.py

      - name: 启动 Clash 并检查状态
        run: |
          nohup clash -d . -f config.yaml &
          echo "Clash 已在后台启动..."
          sleep 5 # 等待 Clash 启动

          # 检查 Clash API 是否可用
          until curl -s --fail http://127.0.0.1:9090 > /dev/null 2>&1; do
            echo "等待 Clash API 启动..."
            sleep 2
          done
          echo "Clash API 已启动。"

      - name: 运行测试脚本
        run: python test_nodes.py

      - name: 提交结果
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/sp.txt
          git commit -m "更新有效节点" || echo "无更改"
          git push
