name: Test Proxy Nodes with Clash
on: [push, workflow_dispatch]
jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 安装 Clash
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          # Fetch API data
          API_URL="https://api.github.com/repos/Dreamacro/clash/releases/latest"
          API_RESPONSE=$(curl -s "$API_URL")
          # Debug: Output the raw API response
          echo "API Response:"
          echo "$API_RESPONSE" | jq '.' || echo "Failed to parse API response"
          # Check if .assets exists and is not null
          ASSETS=$(echo "$API_RESPONSE" | jq -r '.assets')
          if [ "$ASSETS" == "null" ] || [ -z "$ASSETS" ]; then
            echo "错误：API 返回的 .assets 字段为空或不存在。"
            echo "请检查网络连接或 Clash 项目的最新发布版本。"
            exit 1
          fi
          # Extract the download URL
          LATEST_URL=$(echo "$API_RESPONSE" | jq -r '.assets[] | select(.name | contains("linux-amd64")) | .browser_download_url')
          if [ -z "$LATEST_URL" ]; then
            echo "未能找到包含 'linux-amd64' 的下载链接，请检查资产名称或 API 数据。"
            exit 1
          fi
          # Download and install Clash
          wget "$LATEST_URL" -O clash.gz
          gunzip clash.gz
          chmod +x clash
          sudo mv clash /usr/local/bin/clash
          clash -v

      - name: 生成 Clash 配置文件
        run: python generate_config.py

      - name: 运行测试脚本
        run: python test_nodes.py

      - name: 提交结果
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/sp.txt
          git commit -m "更新有效节点" || echo "无更改"
          git push
