
name: Filter Clash Nodes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  filter_nodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 安装依赖
        run: pip install -r ./requirements.txt
      - name:  安装 pysocks
        run: pip install pysocks
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml dnspython

      - name: Make Clash binary executable
        run: |
          chmod +x clash/clash-linux

      - name: Run node filtering script
        run: |
          python filter_nodes.py
      - name: 提交更改
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add data/google.yaml
          git commit -m "${{ github.workflow }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git pull --rebase
