name: Filter Clash Nodes

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  filter-nodes:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyyaml requests

      - name: Make Clash executable
        run: |
          chmod +x ./clash/clash-linux

      - name: Run filter script
        run: |
          python filter_nodes.py

      - name: Upload result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: google-yaml
          path: data/google.yaml
