name: Test Proxy Nodes with Clash
on: [push, workflow_dispatch]
jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 安装 Clash
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          LATEST_URL=$(curl -s https://api.github.com/repos/Dreamacro/clash/releases/latest | jq -r '.assets[] | select(.name | contains("linux-amd64")) | .browser_download_url')
          if [ -z "$LATEST_URL" ]; then
            echo "未能获取 Clash 下载链接，请检查网络或 API 状态"
            exit 1
          fi
          wget "$LATEST_URL" -O clash.gz
          gunzip clash.gz
          chmod +x clash
          sudo mv clash /usr/local/bin/clash
          clash -v

      - name: 生成 Clash 配置文件
        run: python generate_config.py

      - name: 运行测试脚本
        run: python test_nodes.py

      - name: 提交结果
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/sp.txt
          git commit -m "更新有效节点" || echo "无更改"
          git push
