name: Test and Generate Clash Config

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Make Clash Executable
      run: chmod +x clash/clash-linux

    - name: Generate Clash Config
      run: python generate_config.py

    - name: Run Node Test
      run: python test_nodes.py

    - name: Upload sp.txt
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sp.txt
        path: data/sp.txt

    - name: Upload config.yaml
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: config.yaml
        path: config.yaml
