name: Test Proxies

on: [push]  # 触发条件：每次 push 时运行

jobs:
  test:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取仓库代码

      - name: Set up Python
        uses: actions/setup-python@v2  # 设置 Python 环境
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyyaml requests  # 安装脚本依赖

      - name: Ensure Clash is executable
        run: |
          chmod +x clash/clash  # 确保 Clash 二进制文件可执行

      - name: Run proxy test script
        run: |
          python test_proxies.py  # 运行脚本
