

name: Test Proxies


on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'all_clash.py'
  schedule:
    - cron: '30 0/3 * * *'  # 每天UTC时间00:00自动运行

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限设置
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        # 使用SSH方式克隆仓库
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        persist-credentials: true
        
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

   # 安装 Python 依赖
    - name: Install dependencies
      run: |
        pip install requests pyyaml

    # 下载并安装 Clash
    - name: Download and install Clash
      run: |
        wget https://github.com/Dreamacro/clash/releases/download/v1.18.0/clash-linux-amd64-v1.18.0.gz
        gunzip clash-linux-amd64-v1.18.0.gz
        chmod +x clash-linux-amd64-v1.18.0
        sudo mv clash-linux-amd64-v1.18.0 /usr/local/bin/clash
        clash -v

    # 运行代理测试脚本
    - name: Run proxy test script
      run: python test_proxies.py

    # 调试：检查文件是否存在
    - name: Check output file
      run: ls -l data/2.yaml

    # 上传测试结果
    - name: Upload results
      uses: actions/upload-artifact@v3  # 更新到 v3
      with:
        name: available-proxies
        path: data/2.yaml
