name: Run Clash Proxy Test

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发工作流

jobs:
  test-proxies:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出仓库代码

      - name: Create clash directory
        run: mkdir -p /clash  # 创建 /clash 目录（绝对路径）

      - name: Download Clash binary
        run: |
          wget -O /clash/clash-linux https://example.com/path/to/clash-linux
          chmod +x /clash/clash-linux  # 设置执行权限
        # 请将 https://example.com/path/to/clash-linux 替换为实际的 Clash 二进制文件下载链接

      - name: Download clash.yaml
        run: |
          wget -O /clash/clash.yaml https://example.com/path/to/clash.yaml
        # 请将 https://example.com/path/to/clash.yaml 替换为实际的 clash.yaml 下载链接

      - name: Download Country.mmdb
        run: |
          wget -O /clash/Country.mmdb https://example.com/path/to/Country.mmdb
        # 请将 https://example.com/path/to/Country.mmdb 替换为实际的 Country.mmdb 下载链接

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 设置 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml  # 安装脚本所需的 Python 库

      - name: Run proxy test script
        run: python test_proxies.py  # 运行你的 Python 脚本

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: available-proxies
          path: /clash/2.yaml  # 上传生成的可用代理文件
