name: GitHub Code Scanner

on:
  push:
    paths:
      - 'github_scanner.py'
  schedule:
    - cron: '0 */12 * * *' # 每 12 小时自动跑一次
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Run Scanner
        env:
          BOT: ${{ secrets.BOT }} # 这里对应你截图里的 Name
        run: python github_scanner.py

      - name: Commit Results
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Scanner-Bot"
          git add discovered_sites.txt
          if [ -n "$(git status --porcelain discovered_sites.txt)" ]; then
            git commit -m "New assets found [skip ci]"
            git push
          else
            echo "No new results"
          fi
